// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251006004753_InitialCoreModel")]
    partial class InitialCoreModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CancellationReason")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<bool>("IsReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reviewed");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<Guid>("SitterProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("sitter_profile_id");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_bookings_pet_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_owner_created");

                    b.HasIndex("SitterProfileId", "StartUtc", "EndUtc")
                        .HasDatabaseName("ix_bookings_sitter_period");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Domain.Owners.OwnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("DefaultCareNotes")
                        .HasColumnType("varchar(800)")
                        .HasColumnName("default_care_notes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PreferredTimezone")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("preferred_timezone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_owner_profiles");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_owner_profiles_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_owner_profiles_user_id");

                    b.ToTable("owner_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Pets.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("breed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_pets_owner_id");

                    b.HasIndex("OwnerId", "Type")
                        .HasDatabaseName("ix_pets_owner_type");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("Domain.Sitters.SitterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(800)")
                        .HasColumnName("bio");

                    b.Property<int>("CompletedBookings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_bookings");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("ServicesOffered")
                        .HasColumnType("integer")
                        .HasColumnName("services_offered");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sitter_profiles");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_sitter_profiles_is_active");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sitter_profiles_user_id");

                    b.ToTable("sitter_profiles", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("Roles")
                        .HasColumnType("integer")
                        .HasColumnName("roles");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Bookings.Booking", b =>
                {
                    b.OwnsOne("Domain.Bookings.BookingPrice", "Price", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BaseAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_base_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("varchar(3)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("ServiceFeeAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_service_fee_amount");

                            b1.Property<decimal>("ServiceFeePercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("price_service_fee_percent");

                            b1.Property<decimal>("TotalAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_total_amount");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("Domain.Bookings.BookingCareInstructionSnapshot", "CareInstructionSnapshots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("varchar(400)")
                                .HasColumnName("text");

                            b1.Property<Guid>("booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_booking_care_instruction_snapshots");

                            b1.HasIndex("booking_id")
                                .HasDatabaseName("ix_booking_care_instruction_snapshots_booking_id");

                            b1.ToTable("booking_care_instruction_snapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("booking_id");
                        });

                    b.OwnsMany("Domain.Bookings.BookingStatusHistory", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("ChangedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("changed_at_utc");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<Guid>("booking_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_booking_status_history");

                            b1.HasIndex("booking_id")
                                .HasDatabaseName("ix_booking_status_history_booking_id");

                            b1.ToTable("booking_status_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("booking_id");
                        });

                    b.Navigation("CareInstructionSnapshots");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Domain.Owners.OwnerProfile", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OwnerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("varchar(120)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("varchar(80)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("varchar(200)")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("varchar(40)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("StateOrProvince")
                                .IsRequired()
                                .HasColumnType("varchar(120)")
                                .HasColumnName("address_state");

                            b1.HasKey("OwnerProfileId");

                            b1.ToTable("owner_profiles");

                            b1.WithOwner()
                                .HasForeignKey("OwnerProfileId");
                        });

                    b.OwnsMany("Domain.Owners.EmergencyContact", "EmergencyContacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("varchar(150)")
                                .HasColumnName("name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("varchar(60)")
                                .HasColumnName("phone");

                            b1.Property<Guid>("owner_profile_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_owner_emergency_contacts");

                            b1.HasIndex("owner_profile_id")
                                .HasDatabaseName("ix_owner_emergency_contacts_owner_profile_id");

                            b1.ToTable("owner_emergency_contacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("owner_profile_id");
                        });

                    b.Navigation("Address");

                    b.Navigation("EmergencyContacts");
                });

            modelBuilder.Entity("Domain.Pets.Pet", b =>
                {
                    b.OwnsMany("Domain.Pets.CareInstruction", "Instructions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("varchar(400)")
                                .HasColumnName("text");

                            b1.Property<Guid>("pet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_pet_instructions");

                            b1.HasIndex("pet_id")
                                .HasDatabaseName("ix_pet_instructions_pet_id");

                            b1.ToTable("pet_instructions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pet_id");
                        });

                    b.OwnsMany("Domain.Pets.Medical.MedicalEntry", "MedicalEntries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Details")
                                .HasColumnType("varchar(1000)")
                                .HasColumnName("details");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("title");

                            b1.Property<Guid>("pet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_pet_medical_entries");

                            b1.HasIndex("pet_id")
                                .HasDatabaseName("ix_pet_medical_entries_pet_id");

                            b1.ToTable("pet_medical_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pet_id");
                        });

                    b.OwnsMany("Domain.Pets.Medical.PetAllergy", "Allergies", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Notes")
                                .HasColumnType("varchar(500)")
                                .HasColumnName("notes");

                            b1.Property<int>("Severity")
                                .HasColumnType("integer")
                                .HasColumnName("severity");

                            b1.Property<Guid>("pet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_pet_allergies");

                            b1.HasIndex("pet_id")
                                .HasDatabaseName("ix_pet_allergies_pet_id");

                            b1.ToTable("pet_allergies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pet_id");
                        });

                    b.OwnsMany("Domain.Pets.Medical.PetMedication", "Medications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<string>("Dosage")
                                .IsRequired()
                                .HasColumnType("varchar(150)")
                                .HasColumnName("dosage");

                            b1.Property<DateTime?>("EndUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_utc");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Schedule")
                                .IsRequired()
                                .HasColumnType("varchar(250)")
                                .HasColumnName("schedule");

                            b1.Property<DateTime>("StartUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_utc");

                            b1.Property<Guid>("pet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_pet_medications");

                            b1.HasIndex("pet_id")
                                .HasDatabaseName("ix_pet_medications_pet_id");

                            b1.ToTable("pet_medications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pet_id");
                        });

                    b.OwnsMany("Domain.Pets.Medical.PetVaccination", "Vaccinations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AdministeredOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("administered_on_utc");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<DateTime?>("ExpiresOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_on_utc");

                            b1.Property<string>("VaccineName")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("vaccine_name");

                            b1.Property<Guid>("pet_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_pet_vaccinations");

                            b1.HasIndex("pet_id")
                                .HasDatabaseName("ix_pet_vaccinations_pet_id");

                            b1.ToTable("pet_vaccinations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("pet_id");
                        });

                    b.Navigation("Allergies");

                    b.Navigation("Instructions");

                    b.Navigation("MedicalEntries");

                    b.Navigation("Medications");

                    b.Navigation("Vaccinations");
                });

            modelBuilder.Entity("Domain.Sitters.SitterProfile", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Money", "BaseRate", b1 =>
                        {
                            b1.Property<Guid>("SitterProfileId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("base_rate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("varchar(3)")
                                .HasColumnName("base_rate_currency");

                            b1.HasKey("SitterProfileId");

                            b1.ToTable("sitter_profiles");

                            b1.WithOwner()
                                .HasForeignKey("SitterProfileId");
                        });

                    b.OwnsMany("Domain.Sitters.AvailabilitySlot", "Availability", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at")
                                .HasDefaultValueSql("timezone('utc', now())");

                            b1.Property<DateTime>("EndUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("end_utc");

                            b1.Property<DateTime>("StartUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("start_utc");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<Guid>("sitter_profile_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id")
                                .HasName("pk_sitter_availability_slots");

                            b1.HasIndex("sitter_profile_id")
                                .HasDatabaseName("ix_sitter_availability_slots_profile_id");

                            b1.HasIndex("StartUtc", "EndUtc")
                                .HasDatabaseName("ix_sitter_availability_slots_range");

                            b1.ToTable("sitter_availability_slots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("sitter_profile_id");
                        });

                    b.Navigation("Availability");

                    b.Navigation("BaseRate");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ux_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
